// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism } from "@clerk/themes";
import Script from "next/script";
import { UserCreditContextProvider } from "@/providers/UserCredit";
import { MetaMaskProvider } from "@/components/MetaMaskProvider";
import MetaMaskGate from "@/components/MetaMaskGate";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: neobrutalism,
        elements: {
          formButtonPrimary:
            "bg-blue-500 hover:bg-blue-600 text-white font-medium py-2 px-4 rounded focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50 transition-colors roobert-font",
        },
      }}
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
    >
      <Analytics />
      <SpeedInsights />
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <UserCreditContextProvider>
            <MetaMaskProvider>
              
                <Navbar />
                {children}
                <Footer />
              
            </MetaMaskProvider>
            <Script src="https://checkout.razorpay.com/v1/checkout.js" />
          </UserCreditContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
